version: "3"
services:
  app_react:
    build: ./frontend
    container_name: app_react
    volumes:
      - build_react:/var/www/html
    env_file:
      - ./frontend/.env
    depends_on:
      - app_node

  banco:
    image: postgres
    container_name: banco
    env_file:
      - ./backend/.env
    ports:
      - 2345:5432
    restart: always
    volumes:
      - volume_banco:/var/lib/postgresql/data

  cache:
    image: redis:6.2-alpine
    container_name: cache
    ports:
      - 6379:6379
    command: "redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
    restart: always
    volumes: 
      - volume_cache:/data

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react
      - app_node

  app_node:
    build: ./backend
    container_name: app_node
    ports:
      - 4000:4000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://banco:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run dev"
    depends_on:
      - banco
      - cache

volumes:
  build_react:
  volume_banco:
  volume_cache: