version: "3"
services:
  app_react:
    build: ./frontend
    container_name: app_react
    volumes:
      - build_react:/var/www/html
    env_file:
      - ./frontend/.env
    depends_on:
      - app_node

  banco:
    image: postgres
    container_name: banco
    env_file:
      - ./backend/.env
    ports:
      - 2345:5432
    restart: always
    volumes:
      - volume_banco:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - 9736:6379
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    restart: always
    env_file:
      - ./backend/.env
    volumes: 
      - volume_redis:/var/lib/redis/data

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react
      - app_node

  app_node:
    build: ./backend
    container_name: app_node
    ports:
      - 4000:4000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://banco:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run dev"
    depends_on:
      - banco
      - redis

volumes:
  build_react:
  volume_banco:
  volume_redis: